default:
  http_metas:
    content-type: text/html

  metas:
    title:        Planeta PHP.pl
    robots:       index, follow
    description:  planeta php.pl
    keywords:     planeta php php.pl
    language:     pl

  stylesheets:    [default]

  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/effects, utils]

  has_layout:     on
  layout:         layout
